package com.xsm.demo.entity;

import com.wordnik.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class HomageGenealogy {
    /**
     * 族谱ID
     *
     * @mbggenerated
     */
    private Long genealogyId;

    /**
     * 族谱名
     *
     * @mbggenerated
     */
    private String genealogyName;

    /**
     * 创建者用户
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * 姓氏
     *
     * @mbggenerated
     */
    private String surname;

    /**
     * 堂号
     *
     * @mbggenerated
     */
    private String church;

    /**
     * 所在-省
     *
     * @mbggenerated
     */
    private String province;

    /**
     * 所在-市
     *
     * @mbggenerated
     */
    private String city;

    /**
     * 所在-区
     *
     * @mbggenerated
     */
    private String county;

    /**
     * 族谱来源
     *
     * @mbggenerated
     */
    private String source;

    /**
     * 描述
     *
     * @mbggenerated
     */
    private String description;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date rowAddTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date rowUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homage_genealogy.genealogy_id
     *
     * @return the value of homage_genealogy.genealogy_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "族谱ID")
    public Long getGenealogyId() {
        return genealogyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homage_genealogy.genealogy_id
     *
     * @param genealogyId the value for homage_genealogy.genealogy_id
     *
     * @mbggenerated
     */
    public void setGenealogyId(Long genealogyId) {
        this.genealogyId = genealogyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homage_genealogy.genealogy_name
     *
     * @return the value of homage_genealogy.genealogy_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "族谱名")
    public String getGenealogyName() {
        return genealogyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homage_genealogy.genealogy_name
     *
     * @param genealogyName the value for homage_genealogy.genealogy_name
     *
     * @mbggenerated
     */
    public void setGenealogyName(String genealogyName) {
        this.genealogyName = genealogyName == null ? null : genealogyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homage_genealogy.user_id
     *
     * @return the value of homage_genealogy.user_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "创建者用户")
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homage_genealogy.user_id
     *
     * @param userId the value for homage_genealogy.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homage_genealogy.surname
     *
     * @return the value of homage_genealogy.surname
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "姓氏")
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homage_genealogy.surname
     *
     * @param surname the value for homage_genealogy.surname
     *
     * @mbggenerated
     */
    public void setSurname(String surname) {
        this.surname = surname == null ? null : surname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homage_genealogy.church
     *
     * @return the value of homage_genealogy.church
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "堂号")
    public String getChurch() {
        return church;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homage_genealogy.church
     *
     * @param church the value for homage_genealogy.church
     *
     * @mbggenerated
     */
    public void setChurch(String church) {
        this.church = church == null ? null : church.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homage_genealogy.province
     *
     * @return the value of homage_genealogy.province
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "所在-省")
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homage_genealogy.province
     *
     * @param province the value for homage_genealogy.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homage_genealogy.city
     *
     * @return the value of homage_genealogy.city
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "所在-市")
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homage_genealogy.city
     *
     * @param city the value for homage_genealogy.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homage_genealogy.county
     *
     * @return the value of homage_genealogy.county
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "所在-区")
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homage_genealogy.county
     *
     * @param county the value for homage_genealogy.county
     *
     * @mbggenerated
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homage_genealogy.source
     *
     * @return the value of homage_genealogy.source
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "族谱来源")
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homage_genealogy.source
     *
     * @param source the value for homage_genealogy.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homage_genealogy.description
     *
     * @return the value of homage_genealogy.description
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "描述")
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homage_genealogy.description
     *
     * @param description the value for homage_genealogy.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homage_genealogy.row_add_time
     *
     * @return the value of homage_genealogy.row_add_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "创建时间")
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homage_genealogy.row_add_time
     *
     * @param rowAddTime the value for homage_genealogy.row_add_time
     *
     * @mbggenerated
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homage_genealogy.row_update_time
     *
     * @return the value of homage_genealogy.row_update_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "修改时间")
    public Date getRowUpdateTime() {
        return rowUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homage_genealogy.row_update_time
     *
     * @param rowUpdateTime the value for homage_genealogy.row_update_time
     *
     * @mbggenerated
     */
    public void setRowUpdateTime(Date rowUpdateTime) {
        this.rowUpdateTime = rowUpdateTime;
    }
}