package com.xsm.demo.entity;

import com.wordnik.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class HomageLogUserlogin {
    /**
     * 自增ID
     *
     * @mbggenerated
     */
    private Long logLoginId;

    /**
     * 登录IP
     *
     * @mbggenerated
     */
    private String loginIp;

    /**
     * 用户ID
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * 登录账号
     *
     * @mbggenerated
     */
    private String loginPhone;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date rowAddTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date rowUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homage_log_userlogin.log_login_id
     *
     * @return the value of homage_log_userlogin.log_login_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "自增ID")
    public Long getLogLoginId() {
        return logLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homage_log_userlogin.log_login_id
     *
     * @param logLoginId the value for homage_log_userlogin.log_login_id
     *
     * @mbggenerated
     */
    public void setLogLoginId(Long logLoginId) {
        this.logLoginId = logLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homage_log_userlogin.login_ip
     *
     * @return the value of homage_log_userlogin.login_ip
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "登录IP")
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homage_log_userlogin.login_ip
     *
     * @param loginIp the value for homage_log_userlogin.login_ip
     *
     * @mbggenerated
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homage_log_userlogin.user_id
     *
     * @return the value of homage_log_userlogin.user_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "用户ID")
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homage_log_userlogin.user_id
     *
     * @param userId the value for homage_log_userlogin.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homage_log_userlogin.login_phone
     *
     * @return the value of homage_log_userlogin.login_phone
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "登录账号")
    public String getLoginPhone() {
        return loginPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homage_log_userlogin.login_phone
     *
     * @param loginPhone the value for homage_log_userlogin.login_phone
     *
     * @mbggenerated
     */
    public void setLoginPhone(String loginPhone) {
        this.loginPhone = loginPhone == null ? null : loginPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homage_log_userlogin.row_add_time
     *
     * @return the value of homage_log_userlogin.row_add_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "创建时间")
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homage_log_userlogin.row_add_time
     *
     * @param rowAddTime the value for homage_log_userlogin.row_add_time
     *
     * @mbggenerated
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homage_log_userlogin.row_update_time
     *
     * @return the value of homage_log_userlogin.row_update_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "修改时间")
    public Date getRowUpdateTime() {
        return rowUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homage_log_userlogin.row_update_time
     *
     * @param rowUpdateTime the value for homage_log_userlogin.row_update_time
     *
     * @mbggenerated
     */
    public void setRowUpdateTime(Date rowUpdateTime) {
        this.rowUpdateTime = rowUpdateTime;
    }
}