package com.xsm.demo.entity;

import com.wordnik.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class TestSysUserRole {
    /**
     * 主键ID
     *
     * @mbggenerated
     */
    private Long userRoleId;

    /**
     * 用户ID
     *
     * @mbggenerated
     */
    private Long uid;

    /**
     * 角色ID
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date rowAddTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date rowUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_SysUserRole.user_role_id
     *
     * @return the value of test_SysUserRole.user_role_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "主键ID")
    public Long getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_SysUserRole.user_role_id
     *
     * @param userRoleId the value for test_SysUserRole.user_role_id
     *
     * @mbggenerated
     */
    public void setUserRoleId(Long userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_SysUserRole.uid
     *
     * @return the value of test_SysUserRole.uid
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "用户ID")
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_SysUserRole.uid
     *
     * @param uid the value for test_SysUserRole.uid
     *
     * @mbggenerated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_SysUserRole.role_id
     *
     * @return the value of test_SysUserRole.role_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "角色ID")
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_SysUserRole.role_id
     *
     * @param roleId the value for test_SysUserRole.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_SysUserRole.row_add_time
     *
     * @return the value of test_SysUserRole.row_add_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "创建时间")
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_SysUserRole.row_add_time
     *
     * @param rowAddTime the value for test_SysUserRole.row_add_time
     *
     * @mbggenerated
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_SysUserRole.row_update_time
     *
     * @return the value of test_SysUserRole.row_update_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "修改时间")
    public Date getRowUpdateTime() {
        return rowUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_SysUserRole.row_update_time
     *
     * @param rowUpdateTime the value for test_SysUserRole.row_update_time
     *
     * @mbggenerated
     */
    public void setRowUpdateTime(Date rowUpdateTime) {
        this.rowUpdateTime = rowUpdateTime;
    }
}