package com.xsm.demo.entity;

import com.wordnik.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class TestSysPermission {
    /**
     * 权限ID
     *
     * @mbggenerated
     */
    private Long permissionId;

    /**
     * 名称
     *
     * @mbggenerated
     */
    private String name;

    /**
     * 资源类型，[menu|button]
     *
     * @mbggenerated
     */
    private String resourceType;

    /**
     * 资源路径
     *
     * @mbggenerated
     */
    private String url;

    /**
     * 权限字符串,menu例子：role:*，button例子：role:create,role:update,role:delete,role:view
     *
     * @mbggenerated
     */
    private String permission;

    /**
     * 父编号
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * 父编号列表
     *
     * @mbggenerated
     */
    private String parentIds;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date rowAddTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date rowUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_SysPermission.permission_id
     *
     * @return the value of test_SysPermission.permission_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "权限ID")
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_SysPermission.permission_id
     *
     * @param permissionId the value for test_SysPermission.permission_id
     *
     * @mbggenerated
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_SysPermission.name
     *
     * @return the value of test_SysPermission.name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "名称")
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_SysPermission.name
     *
     * @param name the value for test_SysPermission.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_SysPermission.resource_type
     *
     * @return the value of test_SysPermission.resource_type
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "资源类型，[menu|button]")
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_SysPermission.resource_type
     *
     * @param resourceType the value for test_SysPermission.resource_type
     *
     * @mbggenerated
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_SysPermission.url
     *
     * @return the value of test_SysPermission.url
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "资源路径")
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_SysPermission.url
     *
     * @param url the value for test_SysPermission.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_SysPermission.permission
     *
     * @return the value of test_SysPermission.permission
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "权限字符串,menu例子：role:*，button例子：role:create,role:update,role:delete,role:view")
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_SysPermission.permission
     *
     * @param permission the value for test_SysPermission.permission
     *
     * @mbggenerated
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_SysPermission.parent_id
     *
     * @return the value of test_SysPermission.parent_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "父编号")
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_SysPermission.parent_id
     *
     * @param parentId the value for test_SysPermission.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_SysPermission.parent_ids
     *
     * @return the value of test_SysPermission.parent_ids
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "父编号列表")
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_SysPermission.parent_ids
     *
     * @param parentIds the value for test_SysPermission.parent_ids
     *
     * @mbggenerated
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds == null ? null : parentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_SysPermission.row_add_time
     *
     * @return the value of test_SysPermission.row_add_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "创建时间")
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_SysPermission.row_add_time
     *
     * @param rowAddTime the value for test_SysPermission.row_add_time
     *
     * @mbggenerated
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_SysPermission.row_update_time
     *
     * @return the value of test_SysPermission.row_update_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "修改时间")
    public Date getRowUpdateTime() {
        return rowUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_SysPermission.row_update_time
     *
     * @param rowUpdateTime the value for test_SysPermission.row_update_time
     *
     * @mbggenerated
     */
    public void setRowUpdateTime(Date rowUpdateTime) {
        this.rowUpdateTime = rowUpdateTime;
    }
}